name: hue_dart
description: A library for creating Philips Hue apps in Flutter and/or AngularDart.
version: 0.2.1
homepage: https://github.com/Jairzinno/hue_dart
author: Jairzinno Henriquez <jairzinnohenriquez@gmail.com>

environment:
  sdk: '>=2.6.1 <3.0.0'

dependencies:
 intl: ^0.17.0
 http: ^0.13.1
 built_value: ^8.0.4
 built_collection: ^5.0.0

dev_dependencies:
  build_runner:
  test: ^1.16.8
  mockito: ^5.0.2
  built_value_generator: ^8.0.4
